feat(auth): Added Firebase authentication for user login.
berkecibir/asset_tracker pull request #3
Opened 2024-12-17 14:16 UTC by berkecibir

2024-12-17 20:50 UTC, TrSaka requested changes

2024-12-17 21:37 UTC, berkecibir commented on android/app/google-services.json
Haklısın gizliyorum şimdi

2024-12-18 10:18 UTC, E-MRE requested changes
ufak tefek eklemeler

2024-12-18 10:18 UTC, E-MRE commented on lib/app/data/models/auth/user_model.dart
> +  UserModel(
const

2024-12-18 10:18 UTC, E-MRE commented on lib/app/data/repository/auth/auth_repository_impl.dart
> +class AuthRepositoryImpl implements AuthRepository {
bu yaklaşım çok doğru değil. bunun bir kaç sebebi var.

- SOLID prensiplerinden Dependency inversion prensibine aykırı bir durum var. Bu sınıf tümüyle FirebaseAuth'a bağımlı kılınmış ve biz bunu pek istemeyiz.
- Diğer bir sorun ise test edilebilirliği zayıf. Dışarıdan müdahale edemediğimiz bir signUp metodumuz var.

Çözüm olarak bir auth service oluşturabilirsin. bu servisi constructor'da istersin. bu sayede bağımlılığını önemli ölçüde azaltarak daha sürdürülebilir bir koda erişirsin.

Bu konuyu toplantıda gündem yaparsan çok daha kapsamlı anlatabilirim.

2024-12-18 10:18 UTC, E-MRE commented on lib/app/data/repository/auth/auth_repository_impl.dart
> +      if (e.code == AppTexts.userNotFound) {
final isUserNotFound = [AppTexts.userNotFound,AppTexts.wrongPassword].contains(e.code);
if(isUserNotFound)....

2024-12-18 10:18 UTC, E-MRE commented on lib/app/data/repository/auth/auth_repository_impl.dart
> +      if (e.code == AppTexts.userNotFound) {
not hem if içerisinde hem else if içerisinde aynı mesajı dönmüşsün. Eğer kasıtlı yaptıysan problem yok ama copy paste yaparken değiştirmeyi unuttuysan aklında bulunsun

2024-12-18 10:18 UTC, E-MRE commented on lib/app/data/services/auth_service.dart
> +  final FirebaseAuth _firebaseAuth = FirebaseAuth.instance;
hem burada firebase auth alıp hem repository de alman kod tekrarı olduğunu düşündürüyor beni.

bu iki sınıfta aynı işleri yapıyor galiba bir gözden geçirmekte fayda var.

2024-12-18 10:18 UTC, E-MRE commented on lib/app/presentation/login/page/login_page.dart
> +                  onPressed: () async {
onPressed: () async => await _onSigInPressed(...),

Future<void> _onSigInPressed () => hadlleSignUp.....

2024-12-18 10:18 UTC, E-MRE commented on lib/app/presentation/widgets/auth/form_handlers.dart
> +Future<void> handleSignUp({
bunları en azından bir mixin içerisinde yazalım. direkt static metot yapmasak daha tatlı olur. çünkü login olduktan sonra ihtiyaç kalmayacak bu arkadaşlara ramde yer kaplamasınlar

2024-12-21 11:00 UTC, E-MRE requested changes
eline sağlık eklemeler yaptım

2024-12-21 11:00 UTC, E-MRE commented on lib/app/data/repository/auth/auth_repository_impl.dart
> +      final user = await _authService.createUser(email, password);
login

2024-12-21 11:00 UTC, E-MRE commented on lib/app/data/repository/auth/auth_service_impl.dart
> +  Future<User?> createUser(String email, String password) async {
login

2024-12-21 11:00 UTC, E-MRE commented on lib/app/presentation/login/page/login_page.dart
>    TextEditingController passwordController = TextEditingController();
late final viewModel;

2024-12-21 11:00 UTC, E-MRE commented on lib/app/presentation/login/page/login_page.dart
> +    Future _onSignInPressed() async {
fix it

2024-12-21 11:00 UTC, E-MRE commented on lib/app/presentation/login/page/login_page.dart
>    @override
initState(
super...
Future.microtask(()=>viewModel = ....)
print

2024-12-21 11:00 UTC, E-MRE commented on lib/app/presentation/widgets/auth/form_handlers.dart
> +mixin LogInHelper {
mixin LogInHelper on State<LoginPage> {
....
....

initState

değişken tanımı

dispose 

setState

2024-12-21 11:00 UTC, E-MRE commented on lib/app/presentation/widgets/auth/form_handlers.dart
> +  Future<void> handleSignUp({
sign in

2025-01-06 12:49 UTC, merged